services:
  mcp-host:
    container_name: mcp-host
    build:
      context: ./mcp-host
      dockerfile: Dockerfile
    environment:
      - LLM_URL=${LLM_URL:-http://llm:8000}
      - MCP_SERVER_OUTLOOK_URL=${MCP_SERVER_OUTLOOK_URL:-http://mcp-server-outlook:8000/mcp}
      - MCP_SERVER_LINES_URL=${MCP_SERVER_LINES_URL:-http://mcp-server-lines:8000/mcp}
    ports:
      - 8001:8000
    networks:
      - public-network
      - internal-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/').read()"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: ${RESTART_POLICY:-no}

  mcp-server-lines:
    container_name: mcp-server-lines
    build:
      context: ./mcp-server-lines
      dockerfile: Dockerfile
    environment:
      - MCP_HOST_LINES=${MCP_HOST_LINES:-0.0.0.0}
      - MCP_PORT_LINES=${MCP_PORT_LINES:-8000}
    ports:
      - 8000:8000
    networks:
      - public-network
      - internal-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/').read()"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: ${RESTART_POLICY:-no}
    

networks:
  public-network:
    driver: bridge
  internal-network:
    driver: bridge
