[project]
name = "mcp-host"
version = "0.1.0"
description = "MCP Host which interacts with the MCP Server and provides an interface for users to interact with the system."
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.139.2",
    "mcp[cli]>=1.28.1",
    "pydantic-settings>=2.14.2",
    "uvicorn>=0.51.0",
]
